version: "3.8"

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    env_file:
      - ./env/neo4j.env
    restart: unless-stopped

volumes:
  neo4j-data:
